file= open('output.txt', 'w')
print("enter text to write to the file: ")
content = input()
file.write(content)
print("Data successfully written to output.txt")
file.close()

file= open('output.txt', 'a')
file.write("\n")
print("Enter additional text to append: ")
cnte = input()
file.write(cnte)
print("Datta successfully append")
file.close()

file= open('output.txt', 'r')
reading = file.read()
print(reading)
file.close()
